# Generated by Django 5.1.6 on 2025-02-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AlfCos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socio",
            name="id",
        ),
        migrations.AddField(
            model_name="socio",
            name="n_socio",
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
