# Generated by Django 5.1.6 on 2025-02-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AlfCos", "0002_remove_socio_id_socio_n_socio"),
    ]

    operations = [
        migrations.AddField(
            model_name="socio",
            name="c_postal",
            field=models.CharField(default="", max_length=5),
        ),
        migrations.AddField(
            model_name="socio",
            name="foto",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="socio",
            name="sexo",
            field=models.CharField(default="M", max_length=1),
        ),
        migrations.AddField(
            model_name="socio",
            name="strickes",
            field=models.IntegerField(default=0),
        ),
    ]
