# Generated by Django 5.1.6 on 2025-02-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AlfCos", "0003_socio_c_postal_socio_foto_socio_sexo_socio_strickes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prueba",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("telefono", models.CharField(max_length=10)),
            ],
        ),
    ]
