# Generated by Django 5.1.6 on 2025-02-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AlfCos", "0005_usuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dia",
            fields=[
                (
                    "dia",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Taller",
            fields=[
                ("n_taller", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
                ("descripcion", models.CharField(max_length=200)),
                ("monitor", models.CharField(max_length=200)),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                ("plazas", models.IntegerField()),
                ("dia", models.ManyToManyField(to="AlfCos.dia")),
            ],
        ),
    ]
