# Generated by Django 5.1.6 on 2025-03-09 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AlfCos", "0006_dia_taller"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="n_user",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="usuario",
            name="n_socio",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="AlfCos.socio",
            ),
        ),
        migrations.CreateModel(
            name="Clase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inscripcion", models.DateTimeField(auto_now_add=True)),
                (
                    "socio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="AlfCos.socio"
                    ),
                ),
                (
                    "taller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="AlfCos.taller"
                    ),
                ),
            ],
            options={
                "unique_together": {("socio", "taller")},
            },
        ),
    ]
