# Generated by Django 5.1.6 on 2025-03-24 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AlfCos", "0007_usuario_n_user_alter_usuario_n_socio_clase"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoCuenta",
            fields=[
                (
                    "tipo",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TipoEvento",
            fields=[
                (
                    "nombre",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cuenta",
            fields=[
                ("id_cuenta", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=100)),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha", models.DateTimeField()),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AlfCos.tipocuenta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                ("id_evento", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
                ("descripcion", models.CharField(max_length=200)),
                ("fecha_ini", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("num_grupos", models.IntegerField(default=0)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AlfCos.tipoevento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField()),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="AlfCos.cuenta"
                    ),
                ),
                (
                    "socio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="AlfCos.socio"
                    ),
                ),
            ],
            options={
                "unique_together": {("socio", "cuenta", "fecha")},
            },
        ),
        migrations.CreateModel(
            name="CuentaEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField()),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="AlfCos.cuenta"
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="AlfCos.evento"
                    ),
                ),
            ],
            options={
                "unique_together": {("evento", "cuenta", "fecha")},
            },
        ),
        migrations.CreateModel(
            name="Asiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("n_asiento", models.IntegerField()),
                ("fecha", models.DateField()),
                ("n_grupo", models.IntegerField()),
                (
                    "n_socio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="AlfCos.socio",
                    ),
                ),
                (
                    "id_evento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AlfCos.evento",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("id_evento", "n_grupo", "n_asiento"),
                        name="unique_asiento",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ListaEspera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inscripcion", models.DateTimeField(auto_now_add=True)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="AlfCos.evento"
                    ),
                ),
                (
                    "socio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="AlfCos.socio"
                    ),
                ),
            ],
            options={
                "unique_together": {("socio", "evento")},
            },
        ),
    ]
