# Generated by Django 5.1.6 on 2025-03-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AlfCos", "0008_tipocuenta_tipoevento_cuenta_evento_cuota_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socio",
            name="dni",
            field=models.CharField(max_length=9),
        ),
    ]
