# Generated by Django 5.1.6 on 2025-03-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AlfCos", "0009_alter_socio_dni"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="n_asientos",
            field=models.IntegerField(default=0),
        ),
    ]
