# Generated by Django 5.1.6 on 2025-03-30 17:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AlfCos", "0011_alter_asiento_fecha"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuenta",
            name="anulada",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="cuenta",
            name="fecha",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
