# Generated by Django 5.1.6 on 2025-04-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AlfCos", "0012_cuenta_anulada_alter_cuenta_fecha"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipocuenta",
            name="id",
            field=models.AutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tipocuenta",
            name="tipo",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
