# Generated by Django 5.1.6 on 2025-04-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AlfCos", "0013_tipocuenta_id_alter_tipocuenta_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipoevento",
            name="id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tipoevento",
            name="nombre",
            field=models.CharField(max_length=50),
        ),
    ]
