# Generated by Django 5.1.6 on 2025-04-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AlfCos", "0014_tipoevento_id_alter_tipoevento_nombre"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sexo",
            fields=[
                ("nombre", models.CharField(max_length=50)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
