# Generated by Django 5.1.6 on 2025-04-22 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AlfCos", "0015_sexo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socio",
            name="sexo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="AlfCos.sexo",
            ),
        ),
    ]
