# Generated by Django 5.1.6 on 2025-04-25 08:38

import AlfCos.models.socio
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AlfCos", "0016_alter_socio_sexo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Prueba",
        ),
        migrations.RenameField(
            model_name="sexo",
            old_name="id",
            new_name="sexo_id",
        ),
        migrations.AlterField(
            model_name="socio",
            name="foto",
            field=models.ImageField(
                blank=True, null=True, upload_to=AlfCos.models.socio.upload_to
            ),
        ),
    ]
