# Generated by Django 5.1.6 on 2025-06-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AlfCos", "0017_delete_prueba_rename_id_sexo_sexo_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asiento",
            name="nombre",
        ),
        migrations.AddField(
            model_name="cuota",
            name="periodo",
            field=models.CharField(default="1semestre", max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="socio",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
