# Generated by Django 5.1.6 on 2025-06-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AlfCos", "0018_remove_asiento_nombre_cuota_periodo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuentaevento",
            name="subtipo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
