# Generated by Django 5.1.6 on 2025-06-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AlfCos", "0019_cuentaevento_subtipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="subtipo",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
